name: Build

on:
  push:
    paths:
      - package.json
      - pnpm-workspace.yaml
      - .github/workflows/build.yml
      - packages/**
    branches:
      - development
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.16.0
          run_install: true

      - name: pack core
        id: pack
        run: pnpm run pack >> $GITHUB_OUTPUT

      - run: echo ${{ steps.pack.outputs }}

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: core
          path: packages/core/*.tgz

      - name: build examples
        run: pnpm run build:ex