name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    if: "contains(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.16.0
          run_install: true

      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
