name: Create new release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Create new release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: Create a release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref }}

